### ISSUE TITLE
Demo doesn't work on Windows 7 64x

### ISSUE THREAD

**Issue by corthax** [gecko0307/dagon-demo#4]
When launched from cmd:

Warning: no "settings.conf" found, using default configuration
Error: failed to create OpenGL context: Could not create GL context: The operati
on completed successfully.

UPD: On Integrated Intel HD

**Comment by gecko0307** [comment]
Usually this kind of error says that requested OpenGL version is not supported by the driver. Dagon requires at least GL 4.0.
